security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_inmemory: { memory: null }

    firewalls:
        dev:
            pattern: ^/((profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_inmemory
            stateless: true       # Important for APIs

    access_control:
        # Allow all OPTIONS requests (CORS preflight)
        - { path: ^/, roles: PUBLIC_ACCESS, methods: [OPTIONS] }

        # Example: allow anyone to call API endpoints
        - { path: ^/map, roles: PUBLIC_ACCESS }

        # Add more access rules here as needed
